version: '3.1'

services:

    db:
        image: mysql:5
        restart: always
        env_file: .env
        command: --disable-partition-engine-check
        ports: 
            - $DB_PORT:3306
    
    app:
        image: crud_test_task:0.1
        command: npm start
        ports:
            - 3000:3000
