version: '3.1'

services:

    db:
        image: mysql:5.7
        restart: always
        env_file: .env_test
        command: --disable-partition-engine-check
        ports: 
            - 3307:3306        
    
    app:
        build: ./app
        command: npm run test
        env_file: .env_test
        ports:
            - 3000:3000
        volumes: 
            - ./app:/usr/src/app
